### ISSUE TITLE
can't preview live page amendment - 404 error

### ISSUE THREAD

**Issue by stephengold** [jMonkeyEngine/SoftwareStore#9]
I received an e-mail asking me to approve tlf30's live page amendment. A link in the e-mail took me to the Administrator::Store Pages, but the preview link for tlf30's page took me to "https://store.jmonkeyengine.org/preview/amendment/opensource/914900f1-b135-4e60-9742-20ca2c498174" which gave a 404 error.

**Comment by tlf30** [comment]
It looks like the `opensource` in the path is incorrect. The correct preview page is:
https://store.jmonkeyengine.org/preview/amendment/914900f1-b135-4e60-9742-20ca2c498174

**Comment by tlf30** [comment]
Looks like the offending line is here: https://github.com/jMonkeyEngine/SoftwareStore/blob/a8cb1c4592e93a4169136444083afedaf1338ea5/www/admin/pages.html#L153

Not sure why this would be broken for my page and no other pages though, so the issue is probably elsewhere.

**Comment by stephengold** [comment]
This might be the first amendment that's required human review since the Store was moved to the JME domain.

**Comment by riccardobl** [comment]
This doesn't seem to be related to the migration.
The action is mapped here
https://github.com/jMonkeyEngine/SoftwareStore/blob/master/src/main/java/com/jayfella/website/controller/http/PreviewPageController.java#L67
It doesn't expect to have `opensource`  in the path. 
It seems indeed an issue in www/admin/pages.html template, removing/opensource/ from the url should fix it.

**Comment by stephengold** [comment]
Thanks for solving this.

**Comment by stephengold** [comment]
I'm still encountering this issue when I try to review admendments.
